"use client";
import {useEffect,useState} from "react";
import {supabaseBrowser} from "../../lib/supabase-browser";
type F={id:string,name:string,storage_path:string,mime_type:string,size_bytes:number};

export default function Dashboard(){
 const [files,setFiles]=useState<F[]>([]);const [user,setUser]=useState("");const [msg,setMsg]=useState("");const [selected,setSelected]=useState<string[]>([]);const [busy,setBusy]=useState(false);
 async function load(){const s=supabaseBrowser();const {data:{user}}=await s.auth.getUser();if(!user){location.href="/";return}setUser(user.email||"");const {data,error}=await s.from("files").select("*").order("created_at",{ascending:false});if(error)setMsg(error.message);else setFiles(data||[])}
 useEffect(()=>{load()},[]);
 function toggle(id:string){setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
 async function upload(e:React.ChangeEvent<HTMLInputElement>){const chosen=Array.from(e.target.files||[]);if(!chosen.length)return;const s=supabaseBrowser();const {data:{user}}=await s.auth.getUser();if(!user)return;setBusy(true);setMsg("Uploading "+chosen.length+" file"+(chosen.length===1?"":"s")+"…");for(const f of chosen){const path=user.id+"/"+crypto.randomUUID()+"-"+f.name.replace(/[^a-zA-Z0-9._-]/g,"_");const u=await s.storage.from("spex-files").upload(path,f,{upsert:false});if(u.error){setMsg(u.error.message);continue}const ins=await s.from("files").insert({owner_id:user.id,name:f.name,storage_path:path,mime_type:f.type||"application/octet-stream",size_bytes:f.size});if(ins.error){await s.storage.from("spex-files").remove([path]);setMsg(ins.error.message)}}setBusy(false);setMsg("Upload complete.");load();e.target.value=""}
 async function share(f:F){const expires=prompt("Expiry in minutes (blank = no expiry):","60");const pin=prompt("Optional PIN (blank = none):","");const one=confirm("Make this one-time / burn after viewing?");const r=await fetch("/api/shares",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({fileId:f.id,expiresMinutes:expires?Number(expires):null,pin:pin||null,oneTime:one})});const d=await r.json();if(!r.ok){setMsg(d.error||"Could not create share");return}await navigator.clipboard?.writeText(d.url);setMsg("Private share copied to clipboard.")}
 async function shareSelected(){const chosen=files.filter(f=>selected.includes(f.id));if(!chosen.length)return;setBusy(true);const urls:string[]=[];for(const f of chosen){const r=await fetch("/api/shares",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({fileId:f.id,expiresMinutes:60,pin:null,oneTime:false})});const d=await r.json();if(r.ok)urls.push(d.url)}await navigator.clipboard?.writeText(urls.join("\n"));setBusy(false);setMsg(urls.length+" secure link"+(urls.length===1?"":"s")+" copied.")}
 async function logout(){await supabaseBrowser().auth.signOut();location.href="/"}
 return <main className="shell">
  <header className="top"><div><div className="brand-mark"><span>✦</span> Spex</div><div className="muted">{user}</div></div><div className="row"><label className="btn primary">＋ Upload<input hidden multiple type="file" accept="image/*,video/*,application/pdf" onChange={upload}/></label><button className="btn dark" onClick={logout}>Log out</button></div></header>
  <section className="hero"><div className="eyebrow">YOUR PRIVATE CLOUD</div><h1>Your files, under your control.</h1><p>Keep photos, videos and documents private. Select multiple items, upload in batches and create controlled viewing links with expiry, PINs and burn-after-view.</p></section>
  {msg&&<p className={msg.toLowerCase().includes("error")||msg.toLowerCase().includes("not found")?"error":"success"}>{msg}</p>}
  {files.length>0&&<div className="toolbar"><div className="selection-count">{selected.length?selected.length+" selected":"Select files to work with them together"}</div><div className="row">{selected.length>0&&<><button className="btn dark" onClick={()=>setSelected([])}>Clear</button><button className="btn primary" onClick={shareSelected} disabled={busy}>{busy?"Creating…":"Create secure links"}</button></>}</div></div>}
  <section className="grid">{files.map(f=>{const isSelected=selected.includes(f.id);return <article className={"card file"+(isSelected?" selected":"")} key={f.id}><div className="preview"><input className="check" type="checkbox" checked={isSelected} onChange={()=>toggle(f.id)} aria-label={"Select "+f.name}/>{f.mime_type.startsWith("image/")?<span className="preview-icon">▧</span>:f.mime_type.startsWith("video/")?<span className="preview-icon">▶</span>:<span className="preview-icon">▤</span>}<span className="type-pill">{f.mime_type.split("/")[1]?.toUpperCase()||"FILE"}</span></div><div className="filebody"><strong className="file-name">{f.name}</strong><div className="muted">{Math.max(1,Math.round(f.size_bytes/1024))} KB</div><div className="actions"><button className="btn" onClick={()=>share(f)}>Create private link</button></div></div></article>})}</section>
  {!files.length&&<div className="card empty"><div className="preview-icon">＋</div><h2>Your cloud is empty.</h2><p className="muted">Upload photos, videos or documents to start building your private space.</p><label className="btn primary">Upload your first files<input hidden multiple type="file" accept="image/*,video/*,application/pdf" onChange={upload}/></label></div>}
 </main>
}